Allow work with VPCs on user-mode (issue #81)
ingrammicro/concerto pull request #108
Opened 2019-05-16 17:23 UTC by pcantera

Closes #81

![imagen](https://user-images.githubusercontent.com/22797797/57874053-f7dfe980-780f-11e9-881d-edfbad957256.png)

# Description

# Related Issue

# Motivation and Context

# How Has This Been Tested?

# Screenshots (if appropriate)

# Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

# Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-05-17 06:37 UTC, chris-m-h approved these changes

2019-05-17 09:15 UTC, pbanos requested changes
Looks good, but it is not any use to manage vpcs if you cannot manage subnets, I think it should be part of the same issue

2019-05-17 09:25 UTC, pcantera commented
> Looks good, but it is not any use to manage vpcs if you cannot manage subnets, I think it should be part of the same issue

Yes, there's another opened issue about subnets.  This was done in a time window to go ahead with these functionalities.The idea is to include Subnet asap.

Do you prefer to integrate it in current issue?

2019-05-17 13:59 UTC, pcantera commented
Added Subnet management

2019-05-24 09:01 UTC, sjpatino approved these changes
:+1:

2019-05-27 11:03 UTC, pbanos requested changes
As we talked last Friday, we need to include VPN management. Also, missing from both documentation and actual routes, we need a /network/subnets/:subnet_id/servers resource that lists the servers inside a subnet: once that resource is done it should be integrated in this PR as well.

2019-05-28 09:36 UTC, pcantera commented
@pbanos Added:
- VPC discard method
- Subnet list-servers method
- VPN management

2019-05-28 16:36 UTC, pcantera commented on api/network/vpcs_api.go
> +// DiscardVPC deletes a VPC by its ID
detected...

2019-05-29 07:36 UTC, lttito commented
please @pcantera remember to merge PR https://github.com/ingrammicro/tapp/pull/1524 at the same time as this PR.
API documentation is updated

2019-05-29 07:37 UTC, lttito approved these changes
:+1:

2019-05-30 08:02 UTC, pbanos requested changes
Small change requests. I think that other than that it is ready to be merged. Good work! :+1:

2019-05-30 08:02 UTC, pbanos commented on api/network/vpns_api.go
> +func (dm *VPNService) GetVPNListPlans(vpcID string) (vpnPlans []*types.VpnPlan, err error) {
This is not good naming, it should be GetVPNPlanList. As a future refactor (in a separate issue) I propose renaming all these `Get<resource>List` methods as `List<resource>s` though.

2019-05-30 08:02 UTC, pbanos commented on api/types/subnets.go
> +	ServerCreationDisabled bool   `json:"server_creation_disabled,omitempty" header:"SERVER_CREATION_DISABLED" show:"nolist,noshow"`
I'd change the header to `READY FOR SERVERS`

2019-05-30 10:23 UTC, pcantera commented on api/network/vpns_api.go
> +func (dm *VPNService) GetVPNListPlans(vpcID string) (vpnPlans []*types.VpnPlan, err error) {
Done

2019-05-30 11:58 UTC, pcantera commented on api/types/subnets.go
> +	ServerCreationDisabled bool   `json:"server_creation_disabled,omitempty" header:"SERVER_CREATION_DISABLED" show:"nolist,noshow"`
As we have commented, left it as is, since this field is not really shown in user-mode.

2019-06-03 12:37 UTC, pbanos approved these changes
:+1:

2019-06-03 14:40 UTC, merged